Merge pull request #1 from dpastoor/master
dpastoor/vanco-models pull request #3
Opened 2017-04-06 14:00 UTC by nmehta2

let's try this again

2017-04-06 16:28 UTC, dpastoor requested changes

2017-04-06 16:28 UTC, dpastoor commented on lo_2010.cpp
> +Fsga :   ?  : small-for-gestational-age
Set default of 1

2017-04-06 16:28 UTC, dpastoor commented on lo_2010.cpp
> +spiro :   ? : spironolactone (L/kg)
set default of 0

2017-04-06 16:28 UTC, dpastoor commented on lo_2010.cpp
> +double Fsga = ?;
this is how you define values inside your code - you have already set these as parameters so you don't need to re-define them

2017-04-06 16:29 UTC, dpastoor commented
so keep in mind distinguishing between parameters for input, and things you define in `[MAIN]`

the syntax of `double <value> = ...` is you initializing a value to use later on. For exaple the normalization value for wt, etc. If you are already passing that value in as a parameter it is already available so you don't want to define.

2017-04-06 16:40 UTC, nmehta2 commented
Why can't you just use the number 70 instead of creating a parameter in `[MAIN]` for `NORM_WT`? Is it easier to have a parameter which you can change if the norm_wt value changes (ex. different patient demographic)?

2017-04-06 17:46 UTC, dpastoor commented
good question - you are close - the biggest reason is that it makes it much clearer to read, especially as the number of parameters expands. For example

`pow(WT/70, 0.75)` doesn't necessarily convey why 70 was chosen and also starts to become harder to read when in a larger formula

whereas by defining the values above with names, it becomes clearer to read the equations, as well as update/change accordingly.

2017-04-06 17:59 UTC, dpastoor requested changes

2017-04-06 17:59 UTC, dpastoor commented on lo_2010.cpp
>  double CLi = 1.0 * pow((wt/NORM_WT), 0.75) * pow((pma/NORM_PMA), 3.16) * Fsga
ok so looking in the actual publication, this F term is misleading. I originally thought it was a 1/0, but that wouldn't makes sense as if the baby wasn't small for gestantioal age, CLi would be 0. Looking into the actual publication, we see that the full CL equation was actually

```
CL = 1.0 * (wt/70)^0.75*(PMA/30)^3.16*[0.83*SGA + 1.03*(1-SGA)]
```

so we should expand this equation to just have the parameter be called SGA (with a default of 0) and then use this equation.

2017-04-06 19:26 UTC, nmehta2 commented
ah okay, that makes sense! Thank you for explaining!

2017-04-08 20:34 UTC, dpastoor commented on models/andeson_2007.cpp
> +double CLi = 3.83*pow(wt/NORM_WT,0.75)*(pow(pma, 3.68)/(pow(pma, 3.68) + pow(33.3, 3.68)))*(516*pow(e, (0.00823*((PMA-40)/52-40)))/scr)/6)*Fvent;
so these are both incorrect. Think of what you are setting as of now. You are saying multiply by 0, so both CL/V will be 0.

In reality, similar to the lo paper, these are likely placeholders for more complex equations like `(1.5*on_vent)`. The `Fvent` stands, essentially, for fraction corresponding to vent status. We need to actually go through the original anderson paper to find the actual values

2017-04-08 20:35 UTC, dpastoor requested changes
getting closer!

2017-04-08 20:35 UTC, dpastoor commented on models/andeson_2007.cpp
>    ECL : 0.04 : Eta on CL
we will also need to pull out the values for the random effects

2017-04-16 13:40 UTC, dpastoor requested changes
so close!

2017-04-16 13:40 UTC, dpastoor commented on models/lo_2010.cpp
> +  ECL : 0.04 : Eta on CL
@nmehta2 so close! lets just get the lo omega and sigma values and i think you got it!

2017-04-16 13:40 UTC, dpastoor commented on models/lo_2010.cpp
> +double DV = CP*(1+PROP);
check the residual error structure as well. This is only proportional as of now - is there also an additive component?

2017-04-16 20:38 UTC, merged

2017-04-16 20:39 UTC, nmehta2 commented on models/lo_2010.cpp
> +  ECL : 0.04 : Eta on CL
i updated the omega values and the residual error model values! are they correct?

2017-04-16 21:28 UTC, nmehta2 commented on models/lo_2010.cpp
> +double DV = CP*(1+PROP);
added the additive comp! did i write it correctly?

2017-04-23 13:56 UTC, dpastoor commented on models/lo_2010.cpp
> +  ECL : 20.5 : Eta on CL
what are all these values? they still need to be reported as variances, so you were correct in that 0.04 --> 20%CV. Remember the variance to %CV calculation can be approximated by sqrt(variance)*100, so sqrt(0.04)*100 = 20%